#!/usr/bin/env python3
"""
Email Template with Clear Personalization Markers
Shows exactly what gets personalized vs what stays static
"""

def show_template_with_markers():
    """Display email templates with clear personalization markers"""
    
    print("📧 EMAIL TEMPLATES WITH PERSONALIZATION MARKERS")
    print("=" * 70)
    print()
    print("🔍 LEGEND:")
    print("   [DYNAMIC] = Changes per prospect")
    print("   [STATIC]  = Same for everyone")
    print("   [AUTO]    = Auto-generated based on prospect data")
    print()
    
    print("=" * 70)
    print("📧 EMAIL 1: INITIAL OUTREACH")
    print("=" * 70)
    print()
    print("Subject: [DYNAMIC] Similar [AUTO]€850K contract to your [AUTO]Berlin bid")
    print()
    print("Body:")
    print("-" * 50)
    print("[DYNAMIC]Michael,")
    print()
    print("I saw [DYNAMIC]DigitalPartners Ltd bid on the [AUTO]€850K [AUTO]Berlin [AUTO]it & software contract that awarded on [AUTO]September 15, 2024.")
    print()
    print("Just found a similar opportunity:")
    print()
    print("[AUTO]€850K [AUTO]it & software contract")
    print("[AUTO]Hamburg City Government")
    print("Same scope as [AUTO]Berlin")
    print("Deadline: [AUTO]October 10")
    print()
    print("Since you already have the experience from [AUTO]Berlin, this could be a good match.")
    print()
    print("Here's the TED listing: [AUTO]https://ted.europa.eu/udl?uri=TED:NOTICE:[AUTO]TED-123456")
    print()
    print("[STATIC]Alex")
    print("[STATIC]TenderPulse")
    print("-" * 50)
    print()
    
    print("=" * 70)
    print("📧 EMAIL 2: PATTERN RECOGNITION")
    print("=" * 70)
    print()
    print("Subject: [STATIC]Third similar contract this month")
    print()
    print("Body:")
    print("-" * 50)
    print("[DYNAMIC]Michael,")
    print()
    print("Update on [AUTO]it & software opportunities:")
    print()
    print("- [AUTO]Berlin Municipality: [AUTO]€850K (you bid - closed)")
    print("- [AUTO]Hamburg City Government: [AUTO]€935K (closed last week)")
    print("- [AUTO]Munich Government: [AUTO]€1M (open until [AUTO]October 13)")
    print()
    print("Same evaluation criteria across all three. If you qualified for [AUTO]Berlin, [AUTO]Munich Government should be straightforward.")
    print()
    print("[STATIC]Just thought you'd want to know since these follow the same pattern.")
    print()
    print("[STATIC]Alex")
    print("-" * 50)
    print()
    
    print("=" * 70)
    print("📧 EMAIL 3: VALUE-FIRST CLOSE")
    print("=" * 70)
    print()
    print("Subject: [AUTO]Last one - [AUTO]€807K contract matches your [AUTO]Berlin bid exactly")
    print()
    print("Body:")
    print("-" * 50)
    print("[DYNAMIC]Michael,")
    print()
    print("[STATIC]Final email. Found one more that matches your [AUTO]Berlin bid almost exactly:")
    print()
    print("[AUTO]€807K [AUTO]it & software for digital transformation")
    print("[AUTO]Frankfurt Municipality")
    print("Deadline: [AUTO]October 20")
    print()
    print("Same buyer profile, same scope, same budget range as [AUTO]Berlin.")
    print()
    print("[STATIC]If you want alerts when these patterns repeat, I track them systematically: [STATIC]https://tenderpulse.eu/trial")
    print()
    print("[STATIC]Otherwise, best of luck with your current pipeline.")
    print()
    print("[STATIC]Alex")
    print("-" * 50)
    print()
    
    print("=" * 70)
    print("🎯 PERSONALIZATION SUMMARY")
    print("=" * 70)
    print()
    print("✅ DYNAMIC (Changes per prospect):")
    print("   • Contact first name (Michael, Sarah, Pierre, etc.)")
    print("   • Company name (DigitalPartners Ltd, TechCorp GmbH, etc.)")
    print()
    print("✅ AUTO-GENERATED (Based on prospect's lost tender):")
    print("   • Contract value (€850K, €1.2M, €650K, etc.)")
    print("   • City/region (Berlin, Munich, Paris, etc.)")
    print("   • Sector (IT & Software, Data Analytics, etc.)")
    print("   • Award date (September 15, 2024, etc.)")
    print("   • Similar opportunities (Hamburg, Lyon, etc.)")
    print("   • TED tender ID (TED-123456, TED-111111, etc.)")
    print("   • Deadlines (October 10, October 13, etc.)")
    print()
    print("✅ STATIC (Same for everyone):")
    print("   • Email structure and flow")
    print("   • Signature (Alex, TenderPulse)")
    print("   • Trial link (https://tenderpulse.eu/trial)")
    print("   • General messaging")
    print()
    print("🚨 IMPORTANT: Each email is UNIQUE per prospect!")
    print("   No two prospects will receive identical emails.")
    print("   All contract data comes from their specific lost tender.")

if __name__ == "__main__":
    show_template_with_markers()
