[phases.setup]
nixPkgs = ['python311', 'gcc', 'pkg-config']

[phases.install]
cmds = [
    'pip install fastapi uvicorn pydantic httpx python-multipart',
    'pip install --no-cache-dir .'
]

[start]
cmd = 'python railway_deploy.py'