server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: procurement-copilot
          __path__: /var/log/app/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            request_id: request_id
            user_id: user_id

      - timestamp:
          source: timestamp
          format: RFC3339

      - labels:
          level:
          service:
          request_id:
          user_id:

      - output:
          source: message
