"""add outreach system

Revision ID: 0003_add_outreach_system
Revises: 0002_add_alerts_system
Create Date: 2023-10-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision: str = '0003_add_outreach_system'
down_revision: str | None = '0002_add_alerts_system'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create awards table
    op.create_table('awards',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tender_ref', sa.String(length=50), nullable=False),
        sa.Column('award_date', sa.Date(), nullable=False),
        sa.Column('winner_names', postgresql.ARRAY(sa.String(length=255)), nullable=False),
        sa.Column('other_bidders', postgresql.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tender_ref'], ['tenders.tender_ref'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    op.create_index(op.f('ix_awards_tender_ref'), 'awards', ['tender_ref'], unique=False)
    op.create_index('ix_awards_award_date', 'awards', ['award_date'], unique=False)
    
    # Create companies table
    op.create_table('companies',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('domain', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('country', sa.String(length=2), nullable=False),
        sa.Column('is_suppressed', sa.Boolean(), nullable=False),
        sa.Column('last_contacted', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_country'), 'companies', ['country'], unique=False)
    op.create_index('ix_companies_name_country', 'companies', ['name', 'country'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_name_country', table_name='companies')
    op.drop_index(op.f('ix_companies_country'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_awards_award_date', table_name='awards')
    op.drop_index(op.f('ix_awards_tender_ref'), table_name='awards')
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
